name: Build .love

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Windows packages
      id: build-packages
      uses: love-actions/love-actions-windows@v1.1.3
      with:
        love-package: ./game.love
        #icon-path: ./assets/windows/icon.ico
        #rc-path: ./assets/windows/template.rc
        product-name: dice_deluxe
        #app-id: ${{ secrets.APP_ID }}
        #product-website: https://www.example.com
        installer-languages: English.isl ChineseSimplified.isl
        output-folder: "./dist"

    #steps:
      #- name: Build macOS packages
        #id: build-packages
        #uses: love-action/love-actions-macos-portable@v1
        #with:
            #app-name: "Dice Deluxe"
            #bundle-id: "org.love2d.my-game"
            #copyright: "Copyright © 2020-2022 XXX Co. All Rights Reserved."
            #icon-path: ./assets/macOS/icon.icns
            #love-ref: "fc3f5ee6209a0aab9a4d381ed5cd99110f9ff2f2"
            #love-patch: "./love.patch"
            #love-package: "./dice-deluxe.love"
            #libs-path: ./libs
            #extra-assets: ./README.md ./license.txt
            #product-name: "dice_deluxe"
            #version-string: "0.8.0"
            #output-folder: "./dist"
            #account-username: ${{ secrets.APPLE_ACCOUNT_USERNAME }}
            #account-password: ${{ secrets.APPLE_ACCOUNT_PASSWORD }}
            #developer-id-application-base64: ${{ secrets.APPLE_CERT_DEVELOPER_ID_APPLICATION }}
            #developer-id-application-password: ${{ secrets.APPLE_CERT_DEVELOPER_ID_APPLICATION_PWD }}
            #team-id: "${{ secrets.APPLE_DEVELOPER_TEAM_ID }}"
            #developer-id-installer-base64: ${{ secrets.APPLE_CERT_DEVELOPER_ID_INSTALLER }}
            #developer-id-installer-password: ${{ secrets.APPLE_CERT_DEVELOPER_ID_INSTALLER_PWD }}
            #dmg-background-path: ./assets/macOS/dmg.png
            #dmg-icon-position: "287 313"
            #dmg-icon-size: "128"
            #dmg-link-position: "734 313"
            #dmg-text-size: "12"
            #dmg-volume-icon-path: ./assets/macOS/dmg.icns
            #dmg-volume-name: "my_game"
            #dmg-window-position: "200 120"
            #dmg-window-size: "1024 604"
